apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:./
  name: playback-order-nut
  description: Playback Order
  tags:
    - java
    - playback
    - test
spec:
  type: service
  lifecycle: production
  owner: Jiraruekmongkol, Winut (Nut)
